#!/usr/bin/env python3
"""Set up a repository for AI coding agents from one rule source, and keep it right.

commands:
  inventory  report what the repository has: instruction files, path rules, skills, MCP,
             review bots, cloud-agent setup, generators, CI, hook manager, docs, symlinks
             and what every session loads
  layout     plan the canonical layout; --apply writes it, never overwriting a hand-written
             file and never replacing a real directory with a symlink
  generate   write each enabled tool's rule files from the flat rules directory;
             --check writes nothing and lists what would change
  check      the CI gate: CLAUDE.md, symlinks, generated files, rules, links, docs index,
             token budget and the AGENTS.md size cap

Settings live in .ai/agent-setup.json, the tools and their rule formats in targets.json.
Exit codes: 0 clean, 1 findings or changes needed, 2 usage or configuration error.
"""

from __future__ import annotations

import argparse
import glob
import json
import math
import os
import posixpath
import re
import subprocess
import sys
import unicodedata
from dataclasses import dataclass, field, replace
from pathlib import Path
from typing import Callable, Dict, List, Optional, Tuple
from urllib.parse import unquote

SCRIPT_DIRECTORY = Path(__file__).resolve().parent
REGISTRY_CANDIDATES = (SCRIPT_DIRECTORY.parent / "assets" / "targets.json", SCRIPT_DIRECTORY / "targets.json")
CONFIG_FILE = ".ai/agent-setup.json"
GENERATE_COMMAND = "agent_setup.py generate"
LAYOUT_COMMAND = "agent_setup.py layout --apply"
GENERATED_MARKER_PREFIX = "<!-- Generated by agent_setup.py from "
CODERABBIT_BEGIN = "# agent-setup:begin"
CODERABBIT_END = "# agent-setup:end"
CODERABBIT_PARENT_KEYS = ["filePatterns", "code_guidelines", "knowledge_base"]
CLAUDE_IMPORT = "@AGENTS.md"
ALWAYS_TARGETED = "claude-code"
BYTES_PER_TOKEN_VARIABLE = "AGENT_INSTRUCTIONS_BYTES_PER_TOKEN"
TARGET_CATEGORIES = ("interactive-agent", "cloud-agent", "review-bot")
CATEGORIES = TARGET_CATEGORIES + ("generator", "ci", "hook-manager")
REQUIRED_TOOL_KEYS = ("id", "name", "category", "detect", "instructions", "rules", "skills_dir", "mcp_config", "setup_file", "docs")
CONFIG_KEYS = ("targets", "rules_dir", "skills_dir", "docs_dir", "docs_index", "rule_line_limit", "token_budget", "bytes_per_token", "agents_md_max_bytes")
ALWAYS_LOADED_FILES = ("CLAUDE.md", ".claude/CLAUDE.md", "AGENTS.md")
MAX_GLOB_EXPANSIONS = 1000
BUDGET_HEADROOM_PERCENT = 15
BUDGET_STEP = 100
MAX_IMPORT_DEPTH = 4
GITKEEP = ".gitkeep"
GITIGNORE_ENTRIES = (".claude/settings.local.json", "CLAUDE.local.md")
GITIGNORE_ALLOWLISTS = ((".ai", ("rules/", "guidelines/", "skills/", "agent-setup.json")), (".claude", ("rules", "skills", "settings.json")))
YAML_RESERVED_STARTS = "*&!{[|>%@`"

GLOB_DIALECT = """glob dialect of a rule's paths: frontmatter, matched against repository-relative file paths:
  *        any characters except /
  ?        one character except /
  [abc]    one character from the set; [!abc] or [^abc] negates it
  **/      zero or more directories, so **/*.php also matches a root file
  /**      everything below a directory
  {a,b}    alternatives, nested and combined: {src,lib}/**/*.{ts,tsx}; expanded into
           separate globs for every tool that takes a comma-separated list
  \\x       a literal x
A glob is anchored at the repository root: *.php matches root files only, **/*.php any depth.
A leading / is dropped, a trailing / means everything below it, dotfiles match like other
files, and matching is case-sensitive. Quote every glob in the frontmatter: YAML reads a bare
* as an alias, and Claude Code then loads the rule in every session."""


class UsageError(Exception):
    pass


class FrontmatterError(Exception):
    pass


@dataclass(frozen=True)
class RuleTarget:
    format: Optional[str]
    directory: Optional[str]
    also_directories: Tuple[str, ...]
    extension: Optional[str]
    keys: dict


@dataclass(frozen=True)
class Tool:
    id: str
    name: str
    category: str
    detect: tuple
    instructions: Tuple[str, ...]
    rules: Optional[RuleTarget]
    skills_dirs: Tuple[str, ...]
    mcp_configs: Tuple[str, ...]
    setup_files: Tuple[str, ...]
    ignore_files: Tuple[str, ...]
    hooks_files: Tuple[str, ...]
    reads_hooks_from: Tuple[str, ...]
    owns: Tuple[str, ...]
    note: Optional[str]
    docs: str


@dataclass(frozen=True)
class Registry:
    tools: Tuple[Tool, ...]
    defaults: dict
    nested_instruction_names: Tuple[str, ...]
    flagged_files: Tuple[str, ...]
    docs_sites: Tuple[str, ...]
    walk_skip: frozenset

    def tool(self, tool_id: str) -> Tool:
        for tool in self.tools:
            if tool.id == tool_id:
                return tool
        raise UsageError(f"unknown tool {tool_id!r}; the registry knows {', '.join(tool.id for tool in self.tools)}")

    def in_categories(self, categories) -> List[Tool]:
        return [tool for tool in self.tools if tool.category in categories]


@dataclass
class Config:
    targets: List[str]
    rules_dir: str
    skills_dir: str
    docs_dir: str
    docs_index: str
    rule_line_limit: int
    token_budget: Optional[int]
    bytes_per_token: float
    agents_md_max_bytes: int
    from_file: bool


@dataclass
class Rule:
    name: str
    source: str
    text: str
    globs: List[str]
    description: Optional[str]
    exclude_agent: Optional[str]
    body: str
    error: Optional[str]
    owned: bool = False

    @property
    def has_paths(self) -> bool:
        return bool(self.globs)

    @property
    def line_count(self) -> int:
        return self.text.count("\n") + (0 if not self.text or self.text.endswith("\n") else 1)

    @property
    def expanded_globs(self) -> List[str]:
        return unique(candidate for pattern in self.globs for candidate in expand_braces(pattern))

    @property
    def summary(self) -> str:
        return self.description or markdown_title(self.body) or self.name


@dataclass
class Change:
    action: str
    path: str
    content: Optional[str]
    source: str


@dataclass
class Problem:
    message: str
    detail: str = ""


@dataclass
class GenerationPlan:
    changes: List[Change] = field(default_factory=list)
    problems: List[Problem] = field(default_factory=list)
    notes: List[str] = field(default_factory=list)
    outputs: List[str] = field(default_factory=list)


@dataclass
class AlwaysLoaded:
    files: List[Tuple[str, int]]
    missing_imports: List[str]

    @property
    def total_bytes(self) -> int:
        return sum(size for _, size in self.files)

    def tokens(self, bytes_per_token: float) -> int:
        return round(self.total_bytes / bytes_per_token)


@dataclass
class Step:
    status: str
    path: str
    detail: str
    action: Optional[Callable[[], None]] = None


def unique(values) -> list:
    return list(dict.fromkeys(values))


def as_tuple(value) -> tuple:
    if value is None:
        return ()
    if isinstance(value, str):
        return (value,)
    return tuple(value)


def read_text(path: Path) -> str:
    try:
        with open(path, encoding="utf-8", errors="replace", newline="") as handle:
            return handle.read()
    except OSError:
        return ""


def write_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as handle:
        handle.write(content)


def relative_to(root: Path, path: Path) -> str:
    return path.relative_to(root).as_posix()


def normalize_relative(path: str) -> Optional[str]:
    normalized = posixpath.normpath(path)
    if normalized == ".." or normalized.startswith("../") or normalized.startswith("/"):
        return None
    return normalized


def positive_ratio(value) -> float:
    try:
        ratio = float(value)
    except (TypeError, ValueError):
        raise argparse.ArgumentTypeError(f"{value!r} is not a number of bytes per token")
    if isinstance(value, bool) or not math.isfinite(ratio) or ratio <= 0:
        raise argparse.ArgumentTypeError(f"{value!r} must be a finite number above 0 bytes per token")
    return ratio


def load_registry(path: Path) -> Registry:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except OSError as error:
        raise UsageError(f"cannot read the tool registry {path}: {error.strerror}")
    except ValueError as error:
        raise UsageError(f"the tool registry {path} is not valid JSON: {error}")
    tools = [registry_tool(path, entry) for entry in data.get("tools", [])]
    identifiers = [tool.id for tool in tools]
    duplicates = sorted({identifier for identifier in identifiers if identifiers.count(identifier) > 1})
    if duplicates:
        raise UsageError(f"{path}: tool ids must be unique, these repeat: {', '.join(duplicates)}")
    if ALWAYS_TARGETED not in identifiers:
        raise UsageError(f"{path}: the registry must define the {ALWAYS_TARGETED} tool")
    missing_defaults = [key for key in CONFIG_KEYS if key != "targets" and key not in data.get("defaults", {})]
    if missing_defaults:
        raise UsageError(f"{path}: defaults lack {', '.join(missing_defaults)}")
    return Registry(
        tools=tuple(tools),
        defaults=dict(data["defaults"]),
        nested_instruction_names=as_tuple(data.get("nested_instruction_names")),
        flagged_files=as_tuple(data.get("flagged_files")),
        docs_sites=as_tuple(data.get("docs_sites")),
        walk_skip=frozenset(data.get("walk_skip", [])),
    )


def registry_tool(path: Path, entry: dict) -> Tool:
    missing = [key for key in REQUIRED_TOOL_KEYS if key not in entry]
    if missing:
        raise UsageError(f"{path}: tool {entry.get('id', '?')} lacks {', '.join(missing)}")
    if entry["category"] not in CATEGORIES:
        raise UsageError(f"{path}: tool {entry['id']} has category {entry['category']!r}; use one of {', '.join(CATEGORIES)}")
    for detector in entry["detect"]:
        if isinstance(detector, dict):
            try:
                re.compile(detector.get("pattern", ""))
            except re.error as error:
                raise UsageError(f"{path}: tool {entry['id']} has an invalid detect pattern: {error}")
    rules = entry["rules"]
    target = None
    if rules is not None:
        target = RuleTarget(rules.get("format"), rules.get("dir"), as_tuple(rules.get("also_dirs")), rules.get("ext"), dict(rules.get("keys") or {}))
    return Tool(
        id=entry["id"],
        name=entry["name"],
        category=entry["category"],
        detect=tuple(entry["detect"]),
        instructions=as_tuple(entry["instructions"]),
        rules=target,
        skills_dirs=as_tuple(entry["skills_dir"]),
        mcp_configs=as_tuple(entry["mcp_config"]),
        setup_files=as_tuple(entry["setup_file"]),
        ignore_files=as_tuple(entry.get("ignore_file")),
        hooks_files=as_tuple(entry.get("hooks_file")),
        reads_hooks_from=as_tuple(entry.get("reads_hooks_from")),
        owns=as_tuple(entry.get("owns")),
        note=entry.get("note"),
        docs=entry["docs"],
    )


def resolve_registry(argument: Optional[str]) -> Registry:
    if argument:
        return load_registry(Path(argument))
    for candidate in REGISTRY_CANDIDATES:
        if candidate.is_file():
            return load_registry(candidate)
    raise UsageError("cannot find targets.json in ../assets or next to agent_setup.py; pass --registry")


def resolve_root(argument: str) -> Path:
    root = Path(argument).resolve()
    if not root.is_dir():
        raise UsageError(f"{argument} is not a directory")
    return root


def detect_entry(root: Path, entry) -> List[str]:
    if isinstance(entry, dict):
        candidates = detect_entry(root, entry.get("file", ""))
        return [name for name in candidates if (root / name).is_file() and re.search(entry.get("pattern", ""), read_text(root / name))]
    if any(character in entry for character in "*?["):
        return sorted(relative_to(root, Path(match)) for match in glob.glob(os.path.join(glob.escape(str(root)), entry)))
    if entry.endswith("/"):
        return [entry] if (root / entry).is_dir() else []
    return [entry] if os.path.lexists(root / entry) else []


def tool_evidence(root: Path, tool: Tool) -> List[str]:
    return unique(match for entry in tool.detect for match in detect_entry(root, entry))


def detected_targets(root: Path, registry: Registry) -> List[str]:
    found = [tool.id for tool in registry.in_categories(TARGET_CATEGORIES) if tool_evidence(root, tool)]
    return unique([ALWAYS_TARGETED] + found)


def owned_paths(root: Path, registry: Registry) -> List[str]:
    return unique(path for tool in registry.tools if tool.owns and tool_evidence(root, tool) for path in tool.owns)


def config_path(key: str, value) -> str:
    if not isinstance(value, str) or not value.strip():
        raise UsageError(f"{CONFIG_FILE}: {key} must be a relative path")
    normalized = normalize_relative(value.strip().rstrip("/"))
    if normalized is None or normalized == ".":
        raise UsageError(f"{CONFIG_FILE}: {key} must be a path inside the repository, not {value!r}")
    return normalized


def config_count(key: str, value, allow_none: bool = False) -> Optional[int]:
    if value is None and allow_none:
        return None
    if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
        raise UsageError(f"{CONFIG_FILE}: {key} must be a whole number above 0{' or null' if allow_none else ''}, not {value!r}")
    return value


def config_targets(registry: Registry, value) -> List[str]:
    if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
        raise UsageError(f"{CONFIG_FILE}: targets must be a list of tool ids")
    for item in value:
        registry.tool(item)
    return unique(value)


def load_config(root: Path, registry: Registry) -> Config:
    path = root / CONFIG_FILE
    values = {}
    if path.is_file():
        try:
            values = json.loads(read_text(path))
        except ValueError as error:
            raise UsageError(f"{CONFIG_FILE} is not valid JSON: {error}")
        if not isinstance(values, dict):
            raise UsageError(f"{CONFIG_FILE} must hold a JSON object")
        unknown = sorted(set(values) - set(CONFIG_KEYS))
        if unknown:
            raise UsageError(f"{CONFIG_FILE} has unknown keys {', '.join(unknown)}; the known keys are {', '.join(CONFIG_KEYS)}")
    merged = {**registry.defaults, **values}
    if "bytes_per_token" not in values and os.environ.get(BYTES_PER_TOKEN_VARIABLE):
        merged["bytes_per_token"] = os.environ[BYTES_PER_TOKEN_VARIABLE]
    try:
        bytes_per_token = positive_ratio(merged["bytes_per_token"])
    except argparse.ArgumentTypeError as error:
        raise UsageError(f"bytes_per_token: {error}")
    return Config(
        targets=config_targets(registry, values["targets"]) if "targets" in values else detected_targets(root, registry),
        rules_dir=config_path("rules_dir", merged["rules_dir"]),
        skills_dir=config_path("skills_dir", merged["skills_dir"]),
        docs_dir=config_path("docs_dir", merged["docs_dir"]),
        docs_index=config_path("docs_index", merged["docs_index"]),
        rule_line_limit=config_count("rule_line_limit", merged["rule_line_limit"]),
        token_budget=config_count("token_budget", merged["token_budget"], allow_none=True),
        bytes_per_token=bytes_per_token,
        agents_md_max_bytes=config_count("agents_md_max_bytes", merged["agents_md_max_bytes"]),
        from_file=path.is_file(),
    )


def config_document(config: Config) -> str:
    document = {
        "targets": config.targets,
        "rules_dir": config.rules_dir,
        "skills_dir": config.skills_dir,
        "docs_dir": config.docs_dir,
        "docs_index": config.docs_index,
        "rule_line_limit": config.rule_line_limit,
        "token_budget": config.token_budget,
        "bytes_per_token": config.bytes_per_token,
        "agents_md_max_bytes": config.agents_md_max_bytes,
    }
    return json.dumps(document, indent=2) + "\n"


def target_tools(registry: Registry, config: Config) -> List[Tool]:
    return [registry.tool(tool_id) for tool_id in config.targets]


def git_files(root: Path) -> List[str]:
    try:
        completed = subprocess.run(
            ["git", "-C", str(root), "ls-files", "-z", "--cached", "--others", "--exclude-standard"],
            capture_output=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return []
    names = completed.stdout.decode("utf-8", "surrogateescape").split("\0")
    return sorted({name for name in names if name and os.path.lexists(root / name)})


@dataclass(frozen=True)
class IgnorePattern:
    base: str
    expression: re.Pattern
    negated: bool
    directory_only: bool


def gitignore_patterns(root: Path, directory: str) -> List[IgnorePattern]:
    patterns = []
    for raw in read_text(root / directory / ".gitignore").splitlines():
        line = raw.rstrip()
        if not line or line.startswith("#"):
            continue
        negated = line.startswith("!")
        line = line[1:] if negated else line
        line = line[1:] if line.startswith("\\") else line
        directory_only = line.endswith("/")
        line = line.rstrip("/")
        if not line:
            continue
        pattern = line.lstrip("/") if "/" in line else "**/" + line
        patterns.append(IgnorePattern(directory, glob_to_regex(pattern), negated, directory_only))
    return patterns


def is_ignored(relative: str, is_directory: bool, patterns: List[IgnorePattern]) -> bool:
    ignored = False
    for pattern in patterns:
        if pattern.base and not relative.startswith(pattern.base + "/"):
            continue
        if pattern.directory_only and not is_directory:
            continue
        if pattern.expression.match(relative[len(pattern.base) + 1:] if pattern.base else relative):
            ignored = not pattern.negated
    return ignored


def walk_files(root: Path, walk_skip: frozenset) -> List[str]:
    found = []
    pending = {"": gitignore_patterns(root, "")}
    for directory, subdirectories, files in os.walk(root):
        current = Path(directory)
        here = "" if current == root else relative_to(root, current)
        patterns = pending.pop(here, [])
        kept = []
        for name in sorted(subdirectories):
            relative = f"{here}/{name}" if here else name
            if name in walk_skip or is_ignored(relative, True, patterns):
                continue
            if (current / name).is_symlink():
                found.append(relative)
                continue
            pending[relative] = patterns + gitignore_patterns(root, relative)
            kept.append(name)
        subdirectories[:] = kept
        found.extend(relative for relative in (f"{here}/{name}" if here else name for name in files) if not is_ignored(relative, False, patterns))
    return sorted(found)


def repository_files(root: Path, registry: Registry) -> Tuple[List[str], str]:
    listed = git_files(root)
    if listed:
        return listed, "git"
    return walk_files(root, registry.walk_skip), "walk"


def inside_git_checkout(root: Path) -> bool:
    try:
        completed = subprocess.run(["git", "-C", str(root), "rev-parse", "--is-inside-work-tree"], capture_output=True, text=True, check=True)
    except (OSError, subprocess.CalledProcessError):
        return False
    return completed.stdout.strip() == "true"


def split_top_level(text: str, quotes: bool) -> List[str]:
    parts, current, depth, quote, index = [], [], 0, None, 0
    while index < len(text):
        character = text[index]
        if quote:
            current.append(character)
            if character == "\\" and quote == '"' and index + 1 < len(text):
                current.append(text[index + 1])
                index += 2
                continue
            if character == quote:
                quote = None
        elif quotes and character in "\"'":
            quote = character
            current.append(character)
        elif character == "\\" and index + 1 < len(text):
            current.append(text[index:index + 2])
            index += 2
            continue
        elif character in "{[":
            depth += 1
            current.append(character)
        elif character in "}]":
            depth -= 1
            current.append(character)
        elif character == "," and depth <= 0:
            parts.append("".join(current))
            current = []
        else:
            current.append(character)
        index += 1
    parts.append("".join(current))
    return parts


def matching_brace(pattern: str, opening: int) -> Optional[int]:
    depth, index = 0, opening
    while index < len(pattern):
        character = pattern[index]
        if character == "\\":
            index += 2
            continue
        if character == "{":
            depth += 1
        elif character == "}":
            depth -= 1
            if depth == 0:
                return index
        index += 1
    return None


def expandable_brace(pattern: str) -> Optional[Tuple[int, int, List[str]]]:
    index = 0
    while index < len(pattern):
        if pattern[index] == "\\":
            index += 2
            continue
        if pattern[index] == "{":
            closing = matching_brace(pattern, index)
            if closing is not None:
                options = split_top_level(pattern[index + 1:closing], quotes=False)
                if len(options) > 1:
                    return index, closing, options
        index += 1
    return None


def expand_braces(pattern: str) -> List[str]:
    group = expandable_brace(pattern)
    if group is None:
        return [pattern]
    opening, closing, options = group
    expanded = []
    for option in options:
        for candidate in expand_braces(pattern[:opening] + option + pattern[closing + 1:]):
            if candidate not in expanded:
                expanded.append(candidate)
            if len(expanded) > MAX_GLOB_EXPANSIONS:
                raise FrontmatterError(f"the glob {pattern} expands to more than {MAX_GLOB_EXPANSIONS} patterns")
    return expanded


def character_class_end(pattern: str, opening: int) -> Optional[int]:
    index = opening + 1
    if index < len(pattern) and pattern[index] in "!^":
        index += 1
    if index < len(pattern) and pattern[index] == "]":
        index += 1
    closing = pattern.find("]", index)
    return closing if closing != -1 else None


def character_class(content: str) -> str:
    negated = content[:1] in ("!", "^")
    members = (content[1:] if negated else content).replace("\\", "\\\\")
    return f"[^/{members}]" if negated else f"[{members}]"


def glob_to_regex(pattern: str) -> re.Pattern:
    pattern = pattern[1:] if pattern.startswith("/") else pattern
    if pattern.endswith("/"):
        pattern += "**"
    parts, index, length = [], 0, len(pattern)
    while index < length:
        character = pattern[index]
        if character == "\\" and index + 1 < length:
            parts.append(re.escape(pattern[index + 1]))
            index += 2
            continue
        if character == "*":
            end = index
            while end < length and pattern[end] == "*":
                end += 1
            whole_segment = (index == 0 or pattern[index - 1] == "/") and (end == length or pattern[end] == "/")
            if end - index >= 2 and whole_segment:
                parts.append(".*" if end == length else "(?:.*/)?")
                end += 0 if end == length else 1
            else:
                parts.append("[^/]*")
            index = end
            continue
        if character == "?":
            parts.append("[^/]")
            index += 1
            continue
        if character == "[":
            closing = character_class_end(pattern, index)
            if closing is not None:
                parts.append(character_class(pattern[index + 1:closing]))
                index = closing + 1
                continue
        parts.append(re.escape(character))
        index += 1
    return re.compile(r"\A" + "".join(parts) + r"\Z")


def glob_matches_any(pattern: str, files: List[str]) -> bool:
    expressions = [glob_to_regex(candidate) for candidate in expand_braces(pattern)]
    return any(expression.match(name) for name in files for expression in expressions)


FRONTMATTER_KEY = re.compile(r"^([A-Za-z_][\w.-]*)[ \t]*:(?:[ \t]+(.*))?$")
LIST_ITEM = re.compile(r"^[ \t]*-(?:[ \t]+(.*))?$")
STRING_FIELDS = ("paths", "description", "excludeAgent")


def split_frontmatter(text: str) -> Tuple[Optional[List[str]], str]:
    lines = text.lstrip("\ufeff").replace("\r\n", "\n").split("\n")
    if lines[0].rstrip() != "---":
        return None, "\n".join(lines)
    for index in range(1, len(lines)):
        if lines[index].rstrip() in ("---", "..."):
            return lines[1:index], "\n".join(lines[index + 1:])
    raise FrontmatterError("the frontmatter that opens on line 1 never closes with ---")


def closing_double_quote(value: str) -> Optional[int]:
    index = 1
    while index < len(value):
        if value[index] == "\\":
            index += 2
            continue
        if value[index] == '"':
            return index
        index += 1
    return None


def reject_trailing_text(rest: str, line_number: int) -> None:
    if rest.strip() and not rest.strip().startswith("#"):
        raise FrontmatterError(f"line {line_number}: unexpected text after the closing quote")


def parse_yaml_scalar(raw: str, line_number: int, in_flow: bool = False) -> str:
    value = raw.strip()
    if value.startswith('"'):
        closing = closing_double_quote(value)
        if closing is None:
            raise FrontmatterError(f"line {line_number}: the double quote never closes")
        reject_trailing_text(value[closing + 1:], line_number)
        try:
            return json.loads(value[:closing + 1])
        except ValueError:
            raise FrontmatterError(f"line {line_number}: {value[:closing + 1]} uses an escape this reader does not support")
    if value.startswith("'"):
        characters, index = [], 1
        while index < len(value):
            if value[index] == "'":
                if value[index + 1:index + 2] == "'":
                    characters.append("'")
                    index += 2
                    continue
                reject_trailing_text(value[index + 1:], line_number)
                return "".join(characters)
            characters.append(value[index])
            index += 1
        raise FrontmatterError(f"line {line_number}: the single quote never closes")
    bare = re.split(r"[ \t]#", value, maxsplit=1)[0].strip()
    if bare[:1] and bare[0] in YAML_RESERVED_STARTS:
        raise FrontmatterError(f"line {line_number}: {bare} starts with {bare[0]}, which YAML does not read as text; quote it")
    if ": " in bare or bare.endswith(":"):
        raise FrontmatterError(f"line {line_number}: {bare} contains a colon that YAML reads as a key; quote it")
    if in_flow and any(character in bare for character in "{}[]"):
        raise FrontmatterError(f"line {line_number}: {bare} contains a brace or bracket inside [ ]; quote it")
    return bare


def parse_flow_list(raw: str, line_number: int) -> List[str]:
    value = raw.strip()
    closing = matching_bracket(value)
    if closing is None:
        raise FrontmatterError(f"line {line_number}: the [ list never closes on the same line")
    reject_trailing_text(value[closing + 1:], line_number)
    items = split_top_level(value[1:closing], quotes=True)
    return [parse_yaml_scalar(item, line_number, in_flow=True) for item in items if item.strip()]


def matching_bracket(value: str) -> Optional[int]:
    depth, quote, index = 0, None, 0
    while index < len(value):
        character = value[index]
        if quote:
            if character == "\\" and quote == '"':
                index += 2
                continue
            if character == quote:
                quote = None
        elif character in "\"'":
            quote = character
        elif character == "[":
            depth += 1
        elif character == "]":
            depth -= 1
            if depth == 0:
                return index
        index += 1
    return None


def block_list(lines: List[str], index: int, key: str) -> Tuple[List[str], int, Optional[str]]:
    items = []
    while index < len(lines):
        line = lines[index]
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            index += 1
            continue
        item = LIST_ITEM.match(line)
        if not item:
            if line[:1] in (" ", "\t"):
                return items, index, f"line {index + 2}: `{key}:` holds something other than a list of strings"
            break
        try:
            items.append(parse_yaml_scalar(item.group(1) or "", index + 2))
        except FrontmatterError as error:
            return items, index + 1, str(error)
        index += 1
    return items, index, None


def frontmatter_fields(lines: List[str]) -> dict:
    fields = {}
    index = 0
    while index < len(lines):
        match = FRONTMATTER_KEY.match(lines[index])
        index += 1
        if not match or match.group(1) not in STRING_FIELDS:
            continue
        key, inline = match.group(1), (match.group(2) or "").strip()
        if inline and not inline.startswith("#"):
            try:
                fields[key] = parse_flow_list(inline, index + 1) if inline.startswith("[") else parse_yaml_scalar(inline, index + 1)
            except FrontmatterError:
                if key == "paths":
                    raise
            continue
        items, index, problem = block_list(lines, index, key)
        if problem and key == "paths":
            raise FrontmatterError(problem)
        if not problem:
            fields[key] = items
    return fields


def rule_globs(value) -> List[str]:
    if value is None or value == "":
        return []
    if isinstance(value, str):
        return [part.strip() for part in split_top_level(value, quotes=False) if part.strip()]
    globs = []
    for item in value:
        parts = split_top_level(item, quotes=False)
        if len(parts) > 1:
            raise FrontmatterError(f"the glob {item} has a comma outside braces, which comma-separated targets read as two globs; list each glob separately")
        if item.strip():
            globs.append(item.strip())
    return globs


def parse_rule(root: Path, source: str, owned: bool) -> Rule:
    text = read_text(root / source)
    name = posixpath.basename(source)[:-len(".md")]
    try:
        frontmatter, body = split_frontmatter(text)
        fields = frontmatter_fields(frontmatter) if frontmatter is not None else {}
        globs = rule_globs(fields.get("paths"))
        for pattern in globs:
            expand_braces(pattern)
    except FrontmatterError as error:
        return Rule(name, source, text, [], None, None, text, str(error), owned)
    description = fields.get("description") if isinstance(fields.get("description"), str) else None
    exclude_agent = fields.get("excludeAgent") if isinstance(fields.get("excludeAgent"), str) else None
    return Rule(name, source, text, globs, description or None, exclude_agent or None, body.lstrip("\n"), None, owned)


def is_owned(path: str, owned: List[str]) -> bool:
    return any(path == entry.rstrip("/") or (entry.endswith("/") and path.startswith(entry)) for entry in owned)


def read_rules(root: Path, rules_dir: str, owned: List[str]) -> Tuple[List[Rule], List[str]]:
    directory = root / rules_dir
    if not directory.is_dir():
        return [], []
    rules, subdirectories = [], []
    for entry in sorted(os.listdir(directory)):
        relative = f"{rules_dir}/{entry}"
        if (directory / entry).is_dir():
            if not is_owned(relative + "/", owned):
                subdirectories.append(relative)
            continue
        if entry.endswith(".md") and (directory / entry).is_file():
            rules.append(parse_rule(root, relative, is_owned(relative, owned)))
    return rules, subdirectories


FENCE = re.compile(r"^ {0,3}(`{3,}|~{3,})")
INLINE_CODE = re.compile(r"(`+)(?!`).+?(?<!`)\1(?!`)", re.S)
INLINE_LINK = re.compile(r"(!?\[(?:[^\[\]]|\[[^\]]*\])*\]\(\s*<?)([^)\s>]+)(>?(?:\s+(?:\"[^\"]*\"|'[^']*'))?\s*\))")
REFERENCE_DEFINITION = re.compile(r"^( {0,3}\[(?!\^)[^\]]+\]:[ \t]*<?)([^\s>]+)", re.M)
EXTERNAL_TARGET = re.compile(r"^(?:[a-zA-Z][a-zA-Z0-9+.-]*:|//)")
HEADING = re.compile(r"^ {0,3}#{1,6}[ \t]+(.*?)[ \t]*$")
TITLE = re.compile(r"^ {0,3}#[ \t]+(.*?)[ \t]*$")
ATTRIBUTE_ID = re.compile(r"[ \t]*\{:?[ \t]*#([\w-]+)[^}]*\}[ \t]*$")
HTML_ID = re.compile(r"<[a-zA-Z][^>]*?\s(?:id|name)\s*=\s*[\"']([^\"']+)[\"']")
IMPORT_REFERENCE = re.compile(r"(?<![\w@`])@((?:\.{1,2}/)?[\w.-]+(?:/[\w.-]+)*)")
HTML_COMMENT = re.compile(r"<!--.*?-->", re.S)


def classify_fenced_lines(text: str):
    fence = None
    for line in text.splitlines(keepends=True):
        if fence is None:
            opening = FENCE.match(line)
            if opening:
                fence = opening.group(1)
            yield line, bool(opening)
            continue
        closing = line.strip()
        if closing and set(closing) == {fence[0]} and len(closing) >= len(fence):
            fence = None
        yield line, True


def inline_segments(text: str) -> List[Tuple[bool, str]]:
    segments, position = [], 0
    for match in INLINE_CODE.finditer(text):
        if match.start() > position:
            segments.append((False, text[position:match.start()]))
        segments.append((True, match.group(0)))
        position = match.end()
    if position < len(text):
        segments.append((False, text[position:]))
    return segments


def markdown_segments(text: str) -> List[Tuple[bool, str]]:
    segments, prose = [], []
    for line, fenced in classify_fenced_lines(text):
        if fenced:
            segments.extend(inline_segments("".join(prose)))
            prose = []
            segments.append((True, line))
        else:
            prose.append(line)
    segments.extend(inline_segments("".join(prose)))
    return segments


def masked_code(text: str) -> str:
    return "".join(re.sub(r"[^\n]", " ", segment) if is_code else segment for is_code, segment in markdown_segments(text))


def link_matches(text: str) -> List[re.Match]:
    masked = masked_code(text)
    return list(INLINE_LINK.finditer(masked)) + list(REFERENCE_DEFINITION.finditer(masked))


def link_targets(text: str) -> List[str]:
    return [match.group(2) for match in link_matches(text) if not match.group(1).startswith("!")]


def markdown_title(text: str) -> Optional[str]:
    for line, fenced in classify_fenced_lines(text):
        match = None if fenced else TITLE.match(line.rstrip("\r\n"))
        if match:
            return re.sub(r"[ \t]+#+$", "", match.group(1)).strip() or None
    return None


def heading_slug(text: str) -> str:
    text = re.sub(r"!?\[([^\]]*)\]\([^)]*\)", r"\1", text)
    text = re.sub(r"<[^>]+>", "", text).lower()
    return "".join(character for character in text if character in " -_" or unicodedata.category(character)[0] in "LNM").replace(" ", "-")


def markdown_anchors(text: str) -> set:
    anchors, seen = set(), {}
    for line, fenced in classify_fenced_lines(text):
        match = None if fenced else HEADING.match(line.rstrip("\r\n"))
        if not match:
            continue
        content = re.sub(r"(?:^|[ \t]+)#+[ \t]*$", "", match.group(1))
        explicit = ATTRIBUTE_ID.search(content)
        if explicit:
            anchors.add(explicit.group(1).lower())
            content = content[:explicit.start()]
        slug = heading_slug(content)
        anchors.add(f"{slug}-{seen[slug]}" if slug in seen else slug)
        seen[slug] = seen.get(slug, 0) + 1
    anchors.update(identifier.lower() for identifier in HTML_ID.findall(text))
    return anchors


def resolve_link(source: str, path_part: str) -> Optional[str]:
    if path_part.startswith("/"):
        return normalize_relative(path_part.lstrip("/") or ".")
    return normalize_relative(posixpath.join(posixpath.dirname(source), path_part))


def rebased_target(target: str, source_directory: str, output_directory: str) -> str:
    if EXTERNAL_TARGET.match(target) or target.startswith(("#", "/")):
        return target
    path_part, separator, anchor = target.partition("#")
    resolved = posixpath.normpath(posixpath.join(source_directory, path_part))
    rebased = posixpath.relpath(resolved, output_directory or ".")
    if path_part.endswith("/") and not rebased.endswith("/"):
        rebased += "/"
    return rebased + separator + anchor


def rebase_links(body: str, source_directory: str, output_directory: str) -> str:
    if source_directory == output_directory:
        return body
    replacements = sorted(((match.start(2), match.end(2), match.group(2)) for match in link_matches(body)), reverse=True)
    for start, end, target in replacements:
        body = body[:start] + rebased_target(target, source_directory, output_directory) + body[end:]
    return body


def marker_line(rule: Rule) -> str:
    return f"{GENERATED_MARKER_PREFIX}{rule.source}. Edit that file, then run {GENERATE_COMMAND}. -->"


def is_generated(text: str) -> bool:
    try:
        _, body = split_frontmatter(text)
    except FrontmatterError:
        return False
    first = next((line for line in body.split("\n") if line.strip()), "")
    return first.startswith(GENERATED_MARKER_PREFIX)


PLAIN_YAML_TEXT = re.compile(r"^[A-Za-z0-9][A-Za-z0-9 _.,()/+'-]*$")


def yaml_text(value: str) -> str:
    return value if PLAIN_YAML_TEXT.match(value) and not value.endswith(" ") else json.dumps(value, ensure_ascii=False)


def joined_globs(rule: Rule, keys: dict) -> str:
    return keys.get("separator", ",").join(rule.expanded_globs)


def generated_document(header: List[str], rule: Rule, output_path: str) -> str:
    body = rebase_links(rule.body, posixpath.dirname(rule.source), posixpath.dirname(output_path)).rstrip("\n") + "\n"
    frontmatter = ["---", *header, "---", ""] if header else []
    return "\n".join(frontmatter + [marker_line(rule), "", ""]) + body


def cursor_mdc(rule: Rule, target: RuleTarget, output_path: str) -> str:
    keys = target.keys
    header = [f"{keys.get('description', 'description')}: {yaml_text(rule.summary)}"]
    if rule.has_paths:
        header += [f"{keys.get('globs', 'globs')}: {joined_globs(rule, keys)}", f"{keys.get('always_apply', 'alwaysApply')}: false"]
    else:
        header.append(f"{keys.get('always_apply', 'alwaysApply')}: true")
    return generated_document(header, rule, output_path)


def copilot_applyto(rule: Rule, target: RuleTarget, output_path: str) -> str:
    keys = target.keys
    apply_to = joined_globs(rule, keys) if rule.has_paths else keys.get("all_files", "**")
    header = [f"{keys.get('apply_to', 'applyTo')}: {json.dumps(apply_to)}"]
    if rule.exclude_agent:
        header.append(f"{keys.get('exclude_agent', 'excludeAgent')}: {json.dumps(rule.exclude_agent)}")
    return generated_document(header, rule, output_path)


def trigger_globs(rule: Rule, target: RuleTarget, output_path: str) -> str:
    keys = target.keys
    trigger = keys.get("trigger", "trigger")
    if not rule.has_paths:
        return generated_document([f"{trigger}: {keys.get('always_trigger', 'always_on')}"], rule, output_path)
    globs = joined_globs(rule, keys)
    value = json.dumps(globs) if keys.get("quote_globs") else globs
    return generated_document([f"{trigger}: {keys.get('glob_trigger', 'glob')}", f"{keys.get('globs', 'globs')}: {value}"], rule, output_path)


def kiro_filematch(rule: Rule, target: RuleTarget, output_path: str) -> str:
    keys = target.keys
    inclusion = keys.get("inclusion", "inclusion")
    if not rule.has_paths:
        return generated_document([f"{inclusion}: always"], rule, output_path)
    globs = rule.expanded_globs
    pattern = json.dumps(globs[0]) if len(globs) == 1 else "[" + ", ".join(json.dumps(candidate) for candidate in globs) + "]"
    return generated_document([f"{inclusion}: fileMatch", f"{keys.get('pattern', 'fileMatchPattern')}: {pattern}"], rule, output_path)


def cline_paths(rule: Rule, target: RuleTarget, output_path: str) -> str:
    if not rule.has_paths:
        return generated_document([], rule, output_path)
    header = [f"{target.keys.get('paths', 'paths')}:"] + [f"  - {json.dumps(candidate)}" for candidate in rule.expanded_globs]
    return generated_document(header, rule, output_path)


RULE_FILE_FORMATTERS: Dict[str, Callable[[Rule, RuleTarget, str], str]] = {
    "cursor-mdc": cursor_mdc,
    "copilot-applyto": copilot_applyto,
    "trigger-globs": trigger_globs,
    "kiro-filematch": kiro_filematch,
    "cline-paths": cline_paths,
}
LINK_FORMAT = "claude-symlink"
CODERABBIT_FORMAT = "coderabbit-filepatterns"
KNOWN_FORMATS = set(RULE_FILE_FORMATTERS) | {LINK_FORMAT, CODERABBIT_FORMAT}


def rule_error_message(rule: Rule) -> str:
    return f"{rule.source}: cannot read its frontmatter ({rule.error}); Claude Code then loads the rule in every session. Write paths: as a YAML list of quoted globs."


def exclude_agent_problem(rule: Rule, tool: Tool) -> Optional[str]:
    allowed = tool.rules.keys.get("exclude_agent_values", [])
    if rule.exclude_agent and allowed and rule.exclude_agent not in allowed:
        return f"{rule.source}: excludeAgent is {rule.exclude_agent!r}; {tool.name} accepts {', '.join(allowed)}."
    return None


def plan_generation(root: Path, registry: Registry, config: Config, rules: List[Rule]) -> GenerationPlan:
    plan = GenerationPlan()
    plan.problems.extend(Problem(rule_error_message(rule)) for rule in rules if rule.error and not rule.owned)
    erroneous = {rule.name for rule in rules if rule.error}
    sources = [rule for rule in rules if not rule.error and not rule.owned]
    expected: Dict[str, Tuple[str, str, str]] = {}
    coderabbit_targets = []
    enabled = target_tools(registry, config)
    for tool in enabled:
        if tool.rules is None or tool.rules.format is None:
            if tool.rules is not None and sources:
                plan.notes.append(f"{tool.name}: no confirmed format for path rules in {tool.rules.directory} yet, so nothing is generated; it reads AGENTS.md ({tool.docs}).")
            continue
        rule_format = tool.rules.format
        if rule_format not in KNOWN_FORMATS:
            raise UsageError(f"{tool.id} uses the rule format {rule_format!r}, which this agent_setup.py has no formatter for; update the script or remove {tool.id} from targets")
        if rule_format == LINK_FORMAT:
            continue
        if rule_format == CODERABBIT_FORMAT:
            coderabbit_targets.append(tool)
            continue
        formatter = RULE_FILE_FORMATTERS[rule_format]
        for rule in sources:
            problem = exclude_agent_problem(rule, tool)
            if problem:
                plan.problems.append(Problem(problem))
                continue
            output = f"{tool.rules.directory}/{rule.name}{tool.rules.extension}"
            content = formatter(rule, tool.rules, output)
            if output in expected and expected[output][0] != content:
                raise UsageError(f"{expected[output][1]} and {tool.id} would write different content to {output}; give one of them another directory in the registry")
            expected[output] = (content, tool.id, rule.source)
    for output, (content, _, source) in expected.items():
        plan_output(root, output, content, source, plan)
    plan_pruning(root, enabled, expected, erroneous, plan)
    if coderabbit_targets and not erroneous:
        plan_coderabbit(root, coderabbit_targets[0].rules, sources, config, plan)
    plan.problems = unique_problems(plan.problems)
    return plan


def unique_problems(problems: List[Problem]) -> List[Problem]:
    seen, kept = set(), []
    for problem in problems:
        if problem.message not in seen:
            seen.add(problem.message)
            kept.append(problem)
    return kept


def plan_output(root: Path, output: str, content: str, source: str, plan: GenerationPlan) -> None:
    path = root / output
    plan.outputs.append(output)
    parent = path.parent
    while parent != root:
        if os.path.lexists(parent) and not parent.is_dir():
            plan.problems.append(Problem(f"{relative_to(root, parent)} is a file, so {output} cannot be generated from {source}: move that file's content into AGENTS.md or a rule, then delete it."))
            return
        parent = parent.parent
    if not os.path.lexists(path):
        plan.changes.append(Change("create", output, content, source))
        return
    if path.is_symlink() or not path.is_file():
        plan.problems.append(Problem(f"{output} is a symlink or directory, and {source} would generate a file there: remove it or rename the rule."))
        return
    existing = read_text(path)
    if not is_generated(existing):
        plan.problems.append(Problem(f"{output} is hand-written, and {source} would generate a file with the same name: rename one of them; {output} was left alone."))
        return
    if existing != content:
        plan.changes.append(Change("update", output, content, source))


def plan_pruning(root: Path, enabled: List[Tool], expected: dict, erroneous: set, plan: GenerationPlan) -> None:
    locations = unique((tool.rules.directory, tool.rules.extension) for tool in enabled if tool.rules and tool.rules.format in RULE_FILE_FORMATTERS)
    for directory, extension in locations:
        folder = root / directory
        if not folder.is_dir():
            continue
        for entry in sorted(os.listdir(folder)):
            output = f"{directory}/{entry}"
            path = folder / entry
            if not entry.endswith(extension) or output in expected or path.is_symlink() or not path.is_file():
                continue
            if entry[:-len(extension)] in erroneous or not is_generated(read_text(path)):
                continue
            source = generated_source(read_text(path))
            plan.changes.append(Change("delete", output, None, source))


def generated_source(text: str) -> str:
    match = re.search(re.escape(GENERATED_MARKER_PREFIX) + r"(\S+?)\. ", text)
    return match.group(1) if match else "a rule"


def coderabbit_entries(rules: List[Rule], keys: dict) -> List[Tuple[str, str]]:
    return [(rule.source, joined_globs(rule, keys) if rule.has_paths else "**") for rule in rules]


def coderabbit_items(entries: List[Tuple[str, str]], indent: str) -> List[str]:
    lines = []
    for files, apply_to in entries:
        lines.append(f"{indent}- files: {json.dumps(files)}")
        lines.append(f"{indent}  applyTo: {json.dumps(apply_to)}")
    return lines


def coderabbit_block(entries: List[Tuple[str, str]], indent: str, config: Config) -> List[str]:
    return [f"{indent}{CODERABBIT_BEGIN} generated from {config.rules_dir} by {GENERATE_COMMAND}"] + coderabbit_items(entries, indent) + [f"{indent}{CODERABBIT_END}"]


def coderabbit_snippet(entries: List[Tuple[str, str]], config: Config) -> str:
    return "\n".join(["knowledge_base:", "  code_guidelines:", "    filePatterns:"] + coderabbit_block(entries, "      ", config))


def yaml_ancestry(lines: List[str], index: int) -> List[str]:
    parents = []
    target_indent = len(lines[index]) - len(lines[index].lstrip())
    for line in reversed(lines[:index]):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        indent = len(line) - len(line.lstrip())
        key = re.match(r"^\s*([\w.-]+)\s*:\s*(?:#.*)?$", line)
        if indent < target_indent or (indent == target_indent and key and not parents):
            if not key:
                break
            parents.append(key.group(1))
            target_indent = indent
            if indent == 0:
                break
    return parents


def holds_markers(text: str) -> bool:
    return any(line.strip().startswith((CODERABBIT_BEGIN, CODERABBIT_END)) for line in text.splitlines())


def locate_coderabbit_block(text: str, full_path: bool):
    lines = text.splitlines()
    begins = [index for index, line in enumerate(lines) if line.strip().startswith(CODERABBIT_BEGIN)]
    ends = [index for index, line in enumerate(lines) if line.strip().startswith(CODERABBIT_END)]
    if len(begins) != 1 or len(ends) != 1 or ends[0] < begins[0]:
        return f"needs exactly one `{CODERABBIT_BEGIN}` line followed by one `{CODERABBIT_END}` line"
    ancestry = yaml_ancestry(lines, begins[0])
    placed = ancestry == CODERABBIT_PARENT_KEYS if full_path else ancestry == CODERABBIT_PARENT_KEYS[:len(ancestry)]
    if not placed:
        where = ".".join(reversed(ancestry)) or "the top level"
        return f"has its `{CODERABBIT_BEGIN}` line under {where}, not under knowledge_base.code_guidelines.filePatterns"
    indent = lines[begins[0]][:len(lines[begins[0]]) - len(lines[begins[0]].lstrip())]
    return begins[0], ends[0], indent


def coderabbit_files(root: Path, keys: dict) -> Tuple[List[str], List[str]]:
    configs = [name for name in keys.get("config_files", [".coderabbit.yaml"]) if (root / name).is_file()]
    fragments = [name for pattern in keys.get("fragments", []) for name in detect_entry(root, pattern) if (root / name).is_file()]
    return configs, unique(fragments)


def missing_markers_problem(root: Path, keys: dict, configs: List[str], entries: List[Tuple[str, str]], config: Config) -> Problem:
    typescript = keys.get("typescript_config")
    schema = keys.get("schema")
    if configs:
        where = f"under knowledge_base.code_guidelines.filePatterns in {configs[0]}, merging with the keys already there"
    elif typescript and os.path.lexists(root / typescript):
        where = f"in a YAML file under .coderabbit/ that {typescript} imports into knowledge_base.code_guidelines.filePatterns (a .coderabbit.yaml would replace the TypeScript config)"
    else:
        where = f"in a new {keys.get('config_files', ['.coderabbit.yaml'])[0]}" + (f" that starts with # yaml-language-server: $schema={schema}" if schema else "")
    return Problem(
        f"no CodeRabbit config holds the `{CODERABBIT_BEGIN}` and `{CODERABBIT_END}` lines: run {GENERATE_COMMAND} to print the block to paste.",
        f"Paste this {where}, then run {GENERATE_COMMAND} again:\n{coderabbit_snippet(entries, config)}",
    )


def plan_coderabbit(root: Path, target: RuleTarget, rules: List[Rule], config: Config, plan: GenerationPlan) -> None:
    keys = target.keys
    entries = coderabbit_entries(rules, keys)
    configs, fragments = coderabbit_files(root, keys)
    holders = [name for name in configs + fragments if holds_markers(read_text(root / name))]
    if not holders:
        plan.problems.append(missing_markers_problem(root, keys, configs, entries, config))
        return
    if len(holders) > 1:
        plan.problems.append(Problem(f"{' and '.join(holders)} all hold agent-setup markers: keep the block in one file."))
        return
    holder = holders[0]
    plan.outputs.append(holder)
    text = read_text(root / holder)
    located = locate_coderabbit_block(text, full_path=holder in configs)
    if isinstance(located, str):
        plan.problems.append(Problem(
            f"{holder} {located}: run {GENERATE_COMMAND} to print the block to paste.",
            f"Paste this under knowledge_base.code_guidelines.filePatterns in {holder}, merging with the keys already there, then run {GENERATE_COMMAND} again:\n{coderabbit_snippet(entries, config)}",
        ))
        return
    begin, end, indent = located
    newline = "\r\n" if "\r\n" in text else "\n"
    lines = text.splitlines(keepends=True)
    replaced = "".join(lines[:begin + 1] + [line + newline for line in coderabbit_items(entries, indent)] + lines[end:])
    if replaced != text:
        plan.changes.append(Change("update", holder, replaced, config.rules_dir))


def apply_changes(root: Path, changes: List[Change]) -> None:
    for change in changes:
        path = root / change.path
        if change.action == "delete":
            path.unlink()
        else:
            write_file(path, change.content or "")


def change_line(change: Change) -> str:
    if change.action == "delete":
        return f"{change.path} (generated from {change.source}, which is gone)"
    return f"{change.path} (from {change.source})"


def generation_finding(change: Change) -> str:
    if change.action == "create":
        return f"{change.path} is missing for {change.source}: run {GENERATE_COMMAND} and commit the result."
    if change.action == "update":
        return f"{change.path} is out of date with {change.source}: run {GENERATE_COMMAND} and commit the result."
    return f"{change.path} was generated from {change.source}, which no longer exists: run {GENERATE_COMMAND} and commit the deletion."


def claude_md_state(root: Path) -> str:
    claude = root / "CLAUDE.md"
    if claude.is_symlink():
        agents = root / "AGENTS.md"
        return "symlink-to-agents" if agents.exists() and claude.resolve() == agents.resolve() else "symlink-elsewhere"
    if not claude.exists():
        return "absent"
    lines = read_text(claude).lstrip("\ufeff").splitlines()
    if lines and lines[0].strip() == CLAUDE_IMPORT:
        return "imports-agents"
    if any(line.strip() == CLAUDE_IMPORT for line in lines):
        return "import-not-first"
    return "other-content"


CLAUDE_MD_DESCRIPTIONS = {
    "absent": "absent",
    "imports-agents": "line 1 is @AGENTS.md",
    "symlink-to-agents": "a symlink to AGENTS.md; make it a file whose line 1 is @AGENTS.md",
    "symlink-elsewhere": "a symlink to another file",
    "import-not-first": "imports AGENTS.md, but not on line 1",
    "other-content": "holds its own instructions; merge them into AGENTS.md or docs/, then make line 1 @AGENTS.md",
}


def claude_md_first_line(root: Path) -> str:
    lines = read_text(root / "CLAUDE.md").lstrip("\ufeff").splitlines()
    return lines[0].strip() if lines else ""


def instruction_file_findings(root: Path, config: Config) -> List[str]:
    findings = []
    state = claude_md_state(root)
    if state == "absent" and ALWAYS_TARGETED in config.targets:
        findings.append(f"CLAUDE.md is missing: create it with @AGENTS.md on line 1 ({LAYOUT_COMMAND} does), because Claude Code reads AGENTS.md by itself only while no CLAUDE.md or CLAUDE.local.md exists here or in a parent directory.")
    elif state == "symlink-to-agents":
        findings.append(f"CLAUDE.md is a symlink to AGENTS.md: replace it with a file whose line 1 is @AGENTS.md ({LAYOUT_COMMAND} does); a symlink leaves no room for Claude-only lines and breaks on Windows checkouts.")
    elif state == "symlink-elsewhere":
        findings.append(f"CLAUDE.md is a symlink to {os.readlink(root / 'CLAUDE.md')}: make it a file whose line 1 is @AGENTS.md, with that file's instructions moved into AGENTS.md or docs/.")
    elif state in ("import-not-first", "other-content"):
        findings.append(f"line 1 of CLAUDE.md is {claude_md_first_line(root)!r}, not @AGENTS.md: move its content into AGENTS.md or docs/, then make line 1 @AGENTS.md.")
    if not os.path.lexists(root / "AGENTS.md"):
        findings.append(f"AGENTS.md is missing: create it ({LAYOUT_COMMAND} writes a skeleton); it is the one file nearly every agent reads.")
    return findings


def claude_links(tools: List[Tool], config: Config, owned: List[str]) -> List[Tuple[str, str]]:
    links = []
    for tool in tools:
        if tool.rules is None or tool.rules.format != LINK_FORMAT:
            continue
        links.append((tool.rules.directory, config.rules_dir))
        links.extend((directory, config.skills_dir) for directory in tool.skills_dirs)
    return unique((link, target) for link, target in links if link and link != target and not is_owned(link, owned))


def link_expectation(link: str, target: str) -> str:
    return posixpath.relpath(target, posixpath.dirname(link) or ".")


def link_state(root: Path, link: str, target: str) -> Tuple[str, str]:
    path = root / link
    expected = link_expectation(link, target)
    if path.is_symlink():
        actual = os.readlink(path).rstrip("/")
        return ("ok" if actual == expected else "elsewhere"), actual
    if path.is_dir():
        return "directory", ""
    if os.path.lexists(path):
        return "file", ""
    return "missing", ""


def link_findings(root: Path, registry: Registry, config: Config) -> List[str]:
    findings = []
    for link, target in claude_links(target_tools(registry, config), config, owned_paths(root, registry)):
        state, actual = link_state(root, link, target)
        expected = link_expectation(link, target)
        if state == "missing":
            findings.append(f"{link} is missing: make it a symlink to {expected} ({LAYOUT_COMMAND} does), so Claude Code reads {target}.")
        elif state == "directory":
            findings.append(f"{link} is a real directory: move its files into {target}, delete it, then run {LAYOUT_COMMAND} to link it to {expected}.")
        elif state == "file":
            findings.append(f"{link} is a file: replace it with a symlink to {expected}.")
        elif state == "elsewhere":
            findings.append(f"{link} points to {actual}, not {expected}: relink it with ln -sfn {expected} {link}.")
    return findings


def rule_findings(rules: List[Rule], subdirectories: List[str], files: List[str], config: Config) -> List[str]:
    findings = [f"{directory} is a subdirectory: move its rules to the top of {config.rules_dir}, the only level every tool reads." for directory in subdirectories]
    for rule in rules:
        if rule.owned:
            continue
        if rule.line_count > config.rule_line_limit:
            findings.append(f"{rule.source} has {rule.line_count} lines, over the {config.rule_line_limit}-line limit: keep the trap, its reason and a link, and move the explanation to docs/.")
        if rule.error:
            findings.append(rule_error_message(rule))
            continue
        if not rule.has_paths:
            findings.append(f"{rule.source} has no paths: frontmatter, so it loads in every session: scope it to the files it is about, or move the line into AGENTS.md.")
            continue
        for pattern in rule.globs:
            if not glob_matches_any(pattern, files):
                findings.append(f"{rule.source}: the glob {pattern} matches no file in the repository: point it at the files the rule is about, or delete the rule.")
    return findings


def files_with_checked_links(files: List[str], config: Config) -> List[str]:
    def checked(name: str) -> bool:
        if name in ("AGENTS.md", "CLAUDE.md") or name.endswith("/AGENTS.md"):
            return True
        return name.endswith(".md") and (name.startswith(config.rules_dir + "/") or name.startswith(config.docs_dir + "/"))
    return [name for name in files if checked(name)]


def markdown_link_findings(root: Path, files: List[str]) -> List[str]:
    findings, anchor_cache = [], {}
    for source in files:
        path = root / source
        if not path.is_file():
            continue
        for target in link_targets(read_text(path)):
            if EXTERNAL_TARGET.match(target):
                continue
            path_part, _, anchor = target.partition("#")
            path_part = unquote(path_part.split("?", 1)[0])
            resolved = source if not path_part else resolve_link(source, path_part)
            if resolved is None:
                findings.append(f"{source} links to {target}, which points outside the repository: link to a file inside it, or use a full URL.")
                continue
            if not (root / resolved).exists():
                findings.append(f"{source} links to {target}, which does not exist: fix the path (it is relative to {source}) or remove the link.")
                continue
            if anchor and resolved.endswith(".md") and (root / resolved).is_file():
                if resolved not in anchor_cache:
                    anchor_cache[resolved] = markdown_anchors(read_text(root / resolved))
                if unquote(anchor).lower() not in anchor_cache[resolved]:
                    findings.append(f"{source} links to {target}, but {resolved} has no heading with the anchor #{anchor}: link to an existing heading.")
    return findings


def docs_index_findings(root: Path, files: List[str], config: Config) -> List[str]:
    index = config.docs_index
    if not (root / index).is_file():
        return []
    linked = set()
    for target in link_targets(read_text(root / index)):
        if EXTERNAL_TARGET.match(target):
            continue
        path_part = unquote(target.partition("#")[0].split("?", 1)[0])
        resolved = resolve_link(index, path_part) if path_part else None
        if resolved:
            linked.add(resolved.rstrip("/"))
    prefix = config.docs_dir + "/"
    findings = []
    for name in files:
        if not name.startswith(prefix) or not name.endswith(".md") or name == index:
            continue
        if not reachable_from_index(name, linked, config.docs_dir):
            findings.append(f"{name} is not linked from {index}: add a row for it under its subject, so agents starting at the index find it.")
    return findings


def reachable_from_index(name: str, linked: set, docs_dir: str) -> bool:
    if name in linked:
        return True
    directory = posixpath.dirname(name)
    while directory and directory != docs_dir and directory != ".":
        if directory in linked or f"{directory}/README.md" in linked or f"{directory}/index.md" in linked:
            return True
        directory = posixpath.dirname(directory)
    return False


def import_names(text: str) -> List[str]:
    prose = masked_code(HTML_COMMENT.sub("", text))
    return [match.group(1).rstrip(".,;:") for match in IMPORT_REFERENCE.finditer(prose)]


def display_path(root: Path, path: Path) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return str(path)


def always_loaded(root: Path, rules: List[Rule]) -> AlwaysLoaded:
    seen, files, missing = set(), [], []

    def visit(path: Path, depth: int) -> None:
        if not path.is_file():
            return
        real = path.resolve()
        if real in seen:
            return
        seen.add(real)
        text = read_text(path)
        name = display_path(root, path) + (f" -> {os.readlink(path)}" if path.is_symlink() else "")
        files.append((name, len(text.encode("utf-8"))))
        if depth >= MAX_IMPORT_DEPTH:
            return
        for name in import_names(text):
            target = path.parent / name
            if target.is_file():
                visit(target, depth + 1)
            elif name.endswith((".md", ".mdc", ".txt")):
                missing.append(f"{display_path(root, path)} imports @{name}, which does not exist: fix the path or remove the import.")

    for name in ALWAYS_LOADED_FILES:
        visit(root / name, 0)
    for rule in rules:
        if not rule.has_paths:
            visit(root / rule.source, 0)
    return AlwaysLoaded(files, unique(missing))


def budget_findings(loaded: AlwaysLoaded, config: Config) -> List[str]:
    tokens = loaded.tokens(config.bytes_per_token)
    if config.token_budget is None or tokens <= config.token_budget:
        return []
    return [f"every session loads about {tokens} tokens ({loaded.total_bytes} bytes / {config.bytes_per_token}), over the token_budget of {config.token_budget} in {CONFIG_FILE}: move knowledge to docs/ or scope it with a path rule; raise the budget only in a reviewed change."]


def agents_size_findings(root: Path, config: Config) -> List[str]:
    path = root / "AGENTS.md"
    if not path.is_file():
        return []
    size = path.stat().st_size
    if size <= config.agents_md_max_bytes:
        return []
    return [f"AGENTS.md is {size} bytes, over the {config.agents_md_max_bytes}-byte cap (Codex stops reading at 32 KiB): move knowledge to docs/ and leave pointer rows."]


def tracking_findings(root: Path, paths: List[str]) -> List[str]:
    present = [path for path in unique(paths) if os.path.lexists(root / path)]
    if not present or not inside_git_checkout(root):
        return []
    try:
        completed = subprocess.run(
            ["git", "-C", str(root), "status", "--porcelain", "--ignored", "--untracked-files=all", "--", *present],
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return []
    findings = []
    for line in completed.stdout.splitlines():
        status, name = line[:2], line[3:]
        if status == "??":
            findings.append(f"{name} is not in git: git add it, or a clean checkout and CI will not have it.")
        elif status == "!!":
            findings.append(f"{name} is ignored by .gitignore: allowlist it ({LAYOUT_COMMAND} does for .ai and .claude), or a clean checkout and CI will not have it.")
    return findings


def check_findings(root: Path, registry: Registry, config: Config) -> Tuple[List[str], AlwaysLoaded]:
    files, _ = repository_files(root, registry)
    rules, subdirectories = read_rules(root, config.rules_dir, owned_paths(root, registry))
    plan = plan_generation(root, registry, config, rules)
    loaded = always_loaded(root, rules)
    links = [link for link, _ in claude_links(target_tools(registry, config), config, owned_paths(root, registry))]
    findings = (
        instruction_file_findings(root, config)
        + link_findings(root, registry, config)
        + [generation_finding(change) for change in plan.changes]
        + [problem.message for problem in plan.problems]
        + rule_findings(rules, subdirectories, files, config)
        + markdown_link_findings(root, files_with_checked_links(files, config))
        + docs_index_findings(root, files, config)
        + loaded.missing_imports
        + budget_findings(loaded, config)
        + agents_size_findings(root, config)
        + tracking_findings(root, [CONFIG_FILE, "AGENTS.md", "CLAUDE.md", config.rules_dir, *links, *plan.outputs])
    )
    return unique(findings), loaded


def projected_loaded_bytes(root: Path, registry: Registry, config: Config) -> int:
    rules, _ = read_rules(root, config.rules_dir, owned_paths(root, registry))
    total = always_loaded(root, rules).total_bytes
    if not os.path.lexists(root / "AGENTS.md"):
        total += len(agents_skeleton(config).encode("utf-8"))
    if claude_md_state(root) in ("absent", "symlink-to-agents"):
        total += len((CLAUDE_IMPORT + "\n").encode("utf-8"))
    return total


def measured_token_budget(tokens: int) -> int:
    with_headroom = -(-tokens * (100 + BUDGET_HEADROOM_PERCENT) // (100 * BUDGET_STEP)) * BUDGET_STEP
    return max(BUDGET_STEP, with_headroom)


def layout_config(root: Path, registry: Registry, declared: Optional[str]) -> Tuple[Config, str]:
    config = load_config(root, registry)
    if config.from_file:
        return config, ""
    if declared is not None:
        names = [name.strip() for name in declared.split(",") if name.strip()]
        for name in names:
            registry.tool(name)
        config = replace(config, targets=unique([ALWAYS_TARGETED] + names))
    loaded_bytes = projected_loaded_bytes(root, registry, config)
    tokens = round(loaded_bytes / config.bytes_per_token)
    budget = measured_token_budget(tokens)
    derivation = f"token_budget {budget}: every session will load about {tokens} tokens ({loaded_bytes} bytes / {config.bytes_per_token}), plus {BUDGET_HEADROOM_PERCENT}%, rounded up to the next {BUDGET_STEP}"
    return replace(config, token_budget=budget), derivation


def agents_skeleton(config: Config) -> str:
    return "\n".join([
        "# AGENTS.md",
        "",
        "## Commands",
        "",
        "| Task | Command |",
        "| --- | --- |",
        "",
        "## Where to look",
        "",
        "| Subject | Start at |",
        "| --- | --- |",
        f"| All documentation, by subject | [{config.docs_index}]({config.docs_index}) |",
        f"| Rules for specific paths: read the files whose `paths` match the file you change | [{config.rules_dir}/]({config.rules_dir}/) |",
        "",
    ])


def docs_index_skeleton() -> str:
    return "# Documentation\n\n| Subject | Document |\n| --- | --- |\n"


def config_step(root: Path, config: Config, declared: Optional[str], budget_derivation: str) -> Step:
    if config.from_file:
        detail = "exists; layout never rewrites it" + ("; edit targets there instead of passing --targets" if declared else "")
        return Step("keep", CONFIG_FILE, detail)
    return Step("create", CONFIG_FILE, f"targets {', '.join(config.targets)}; {budget_derivation}", lambda: write_file(root / CONFIG_FILE, config_document(config)))


def agents_step(root: Path, config: Config) -> Step:
    path = root / "AGENTS.md"
    if path.is_symlink():
        return Step("manual", "AGENTS.md", f"is a symlink to {os.readlink(path)}: replace it with a real file holding the instructions, then make CLAUDE.md import it")
    if path.exists():
        return Step("keep", "AGENTS.md", "exists")
    return Step("create", "AGENTS.md", "skeleton with a commands table and a pointer table", lambda: write_file(path, agents_skeleton(config)))


def replace_claude_symlink(root: Path) -> None:
    (root / "CLAUDE.md").unlink()
    write_file(root / "CLAUDE.md", CLAUDE_IMPORT + "\n")


def claude_step(root: Path) -> Step:
    state = claude_md_state(root)
    path = root / "CLAUDE.md"
    if state == "absent":
        return Step("create", "CLAUDE.md", "line 1 is @AGENTS.md", lambda: write_file(path, CLAUDE_IMPORT + "\n"))
    if state == "imports-agents":
        return Step("keep", "CLAUDE.md", "line 1 is @AGENTS.md")
    if state == "symlink-to-agents":
        return Step("update", "CLAUDE.md", "replace the symlink to AGENTS.md with a file whose line 1 is @AGENTS.md", lambda: replace_claude_symlink(root))
    if state == "symlink-elsewhere":
        return Step("manual", "CLAUDE.md", f"is a symlink to {os.readlink(path)}: move that content into AGENTS.md or docs/, then make CLAUDE.md a file whose line 1 is @AGENTS.md")
    if state == "import-not-first":
        return Step("manual", "CLAUDE.md", "merge by hand: move the content above @AGENTS.md into AGENTS.md or docs/, then make line 1 `@AGENTS.md`")
    return Step("manual", "CLAUDE.md", "merge by hand: move its content into AGENTS.md or docs/, then make line 1 `@AGENTS.md`")


def docs_index_step(root: Path, config: Config) -> Step:
    path = root / config.docs_index
    if path.exists():
        return Step("keep", config.docs_index, "exists")
    return Step("create", config.docs_index, "skeleton index table", lambda: write_file(path, docs_index_skeleton()))


def create_kept_directory(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)
    if not any(path.iterdir()):
        write_file(path / GITKEEP, "")


def directory_step(root: Path, relative: str, purpose: str) -> Step:
    path = root / relative
    if path.is_dir():
        return Step("keep", relative + "/", purpose)
    if os.path.lexists(path):
        return Step("manual", relative, f"is a file, but {purpose} needs a directory here")
    return Step("create", relative + "/", f"{purpose}, with {GITKEEP} so git keeps it", lambda: create_kept_directory(path))


def skills_steps(root: Path, registry: Registry, config: Config) -> List[Step]:
    generators = [tool for tool in registry.in_categories(("generator",)) if tool.skills_dirs and tool_evidence(root, tool)]
    if not generators:
        return [directory_step(root, config.skills_dir, "the one skills directory")]
    steps = [directory_step(root, directory, f"hand-written skills that {tool.name} copies into {config.skills_dir}") for tool in generators for directory in tool.skills_dirs]
    if not (root / config.skills_dir).exists():
        steps.append(Step("note", config.skills_dir, f"is generated by {', '.join(tool.name for tool in generators)}; run its install command to fill it"))
    return steps


def make_symlink(path: Path, target: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    os.symlink(target, path)


def link_steps(root: Path, registry: Registry, config: Config) -> List[Step]:
    steps = []
    for link, target in claude_links(target_tools(registry, config), config, owned_paths(root, registry)):
        state, actual = link_state(root, link, target)
        expected = link_expectation(link, target)
        path = root / link
        if state == "ok":
            steps.append(Step("keep", link, f"-> {expected}"))
        elif state == "missing":
            steps.append(Step("link", link, f"-> {expected}", lambda path=path, expected=expected: make_symlink(path, expected)))
        elif state == "directory":
            steps.append(Step("manual", link, f"is a real directory, which layout never replaces: move its contents into {target}, delete it, then run layout again"))
        elif state == "file":
            steps.append(Step("manual", link, f"is a file: remove it, then run layout again to link it to {expected}"))
        else:
            steps.append(Step("manual", link, f"points to {actual}, not {expected}: remove it, then run layout again"))
    return steps


def gitignore_update(original: str) -> Tuple[str, List[str]]:
    newline = "\r\n" if "\r\n" in original else "\n"
    lines = original.splitlines()
    changes = []
    for directory, entries in GITIGNORE_ALLOWLISTS:
        wholesale = {variant for name in (directory, "/" + directory) for variant in (name, name + "/", name + "/**")}
        star = {directory + "/*", "/" + directory + "/*"}
        position = next((index for index, line in enumerate(lines) if line.strip() in wholesale), None)
        if position is not None:
            changes.append(f"replace {lines[position].strip()} with an allowlist under {directory}/*")
            lines[position] = directory + "/*"
        else:
            position = next((index for index, line in enumerate(lines) if line.strip() in star), None)
            if position is None:
                continue
        present = {line.strip() for line in lines}
        missing = [f"!{directory}/{entry}" for entry in entries if f"!{directory}/{entry}" not in present and f"!/{directory}/{entry}" not in present]
        if missing:
            lines[position + 1:position + 1] = missing
            changes.append(f"allow {', '.join(missing)}")
    present = {line.strip().lstrip("/") for line in lines}
    added = [entry for entry in GITIGNORE_ENTRIES if entry not in present]
    if added:
        lines.extend(added)
        changes.append(f"ignore {', '.join(added)}")
    return newline.join(lines) + newline, changes


def gitignore_step(root: Path) -> Step:
    path = root / ".gitignore"
    updated, changes = gitignore_update(read_text(path) if path.is_file() else "")
    if not changes:
        return Step("keep", ".gitignore", "has the agent entries")
    return Step("update" if path.exists() else "create", ".gitignore", "; ".join(changes), lambda: write_file(path, updated))


def plan_layout(root: Path, registry: Registry, config: Config, declared: Optional[str], budget_derivation: str) -> List[Step]:
    return [
        config_step(root, config, declared, budget_derivation),
        agents_step(root, config),
        claude_step(root),
        docs_index_step(root, config),
        directory_step(root, config.rules_dir, "the one rules source"),
        *skills_steps(root, registry, config),
        *link_steps(root, registry, config),
        gitignore_step(root),
    ]


def describe_file(root: Path, name: str, nested: bool) -> Optional[dict]:
    path = root / name
    if path.is_dir() and not path.is_symlink():
        return None
    entry = {"path": name, "nested": nested}
    if path.is_symlink():
        entry["symlink_to"] = os.readlink(path)
    if path.is_file():
        text = read_text(path)
        entry["bytes"] = len(text.encode("utf-8"))
        entry["lines"] = len(text.splitlines())
    return entry


def instruction_files(root: Path, registry: Registry, files: List[str]) -> List[dict]:
    names = unique(name for tool in registry.tools for name in tool.instructions)
    entries = [entry for entry in (describe_file(root, name, False) for name in names if os.path.lexists(root / name)) if entry]
    listed = {entry["path"] for entry in entries}
    nested = [name for name in files if "/" in name and posixpath.basename(name) in registry.nested_instruction_names and name not in listed]
    return entries + [entry for entry in (describe_file(root, name, True) for name in nested) if entry]


def count_files(path: Path, extensions: Tuple[str, ...]) -> int:
    if path.is_file():
        return 1
    return sum(1 for _, _, names in os.walk(path) for name in names if name.endswith(extensions))


def directory_entry(root: Path, name: str) -> dict:
    path = root / name
    entry = {"path": name}
    if path.is_symlink():
        entry["symlink_to"] = os.readlink(path)
    entry["kind"] = "directory" if path.is_dir() else "file"
    return entry


def path_rule_directories(root: Path, registry: Registry, config: Config) -> List[dict]:
    names = unique([config.rules_dir] + [name for tool in registry.tools if tool.rules for name in (tool.rules.directory, *tool.rules.also_directories) if name])
    entries = []
    for name in names:
        if os.path.lexists(root / name):
            entry = directory_entry(root, name)
            entry["files"] = count_files(root / name, (".md", ".mdc"))
            entries.append(entry)
    return entries


def skills_directories(root: Path, registry: Registry, config: Config) -> List[dict]:
    names = unique([config.skills_dir] + [name for tool in registry.tools for name in tool.skills_dirs])
    entries = []
    for name in names:
        path = root / name
        if os.path.lexists(path):
            entry = directory_entry(root, name)
            entry["skills"] = sum(1 for child in path.iterdir() if (child / "SKILL.md").is_file()) if path.is_dir() else 0
            entries.append(entry)
    return entries


def evidence_rows(registry: Registry, evidence: dict, categories) -> List[dict]:
    return [{"tool": tool.id, "name": tool.name, "evidence": evidence[tool.id]} for tool in registry.in_categories(categories) if evidence[tool.id]]


def existing_paths(root: Path, names) -> List[str]:
    return [name for name in unique(names) if detect_entry(root, name)]


def tool_files(root: Path, tools: List[Tool], attribute: str) -> List[dict]:
    rows = []
    for tool in tools:
        for name in getattr(tool, attribute):
            for match in detect_entry(root, name):
                rows.append({"tool": tool.id, "path": match})
    return rows


def shared_hook_notes(root: Path, tools: List[Tool]) -> List[str]:
    notes = []
    for reader in tools:
        for owner in tools:
            if owner.id == reader.id:
                continue
            shared = [name for name in reader.reads_hooks_from if name in owner.hooks_files]
            if not shared:
                continue
            present = [name for name in shared if os.path.lexists(root / name)]
            state = f"{', '.join(present)} exists" if present else "no such file yet"
            notes.append(f"{reader.name} also runs {owner.name}'s hooks from {' and '.join(shared)} ({state}): write each hook so it is safe in both tools, or turn that reading off in {reader.name}.")
    return notes


def tool_notes(registry: Registry, evidence: dict) -> List[str]:
    notes = []
    for tool in registry.tools:
        if not evidence[tool.id]:
            continue
        if tool.note:
            notes.append(f"{tool.name}: {tool.note}")
        if tool.owns:
            notes.append(f"{tool.name} manages {', '.join(tool.owns)}; agent_setup.py leaves them to it.")
    return notes


def flagged_file_notes(root: Path, registry: Registry) -> List[str]:
    notes = []
    for name in registry.flagged_files:
        if os.path.lexists(root / name):
            readers = [tool.name for tool in registry.tools if name in tool.instructions]
            notes.append(f"{name} is present: {', '.join(readers)} read it; every other tool ignores it, so keep shared rules in AGENTS.md.")
    return notes


def inventory_report(root: Path, registry: Registry, config: Config) -> dict:
    files, listing = repository_files(root, registry)
    rules, _ = read_rules(root, config.rules_dir, owned_paths(root, registry))
    evidence = {tool.id: tool_evidence(root, tool) for tool in registry.tools}
    loaded = always_loaded(root, rules)
    claude = [registry.tool(ALWAYS_TARGETED)]
    targets = target_tools(registry, config)
    return {
        "root": str(root),
        "file_listing": listing,
        "agents_detected": [tool.id for tool in registry.in_categories(TARGET_CATEGORIES) if evidence[tool.id]],
        "targets": config.targets,
        "targets_from": CONFIG_FILE if config.from_file else "detection",
        "instruction_files": instruction_files(root, registry, files),
        "claude_md": claude_md_state(root),
        "path_rule_dirs": path_rule_directories(root, registry, config),
        "skills_dirs": skills_directories(root, registry, config),
        "mcp_configs": existing_paths(root, (name for tool in registry.tools for name in tool.mcp_configs)),
        "ignore_files": existing_paths(root, (name for tool in registry.tools for name in tool.ignore_files)),
        "hooks_files": tool_files(root, list(registry.tools), "hooks_files"),
        "review_bots": evidence_rows(registry, evidence, ("review-bot",)),
        "cloud_agent_setup": tool_files(root, list(registry.tools), "setup_files"),
        "generators": evidence_rows(registry, evidence, ("generator",)),
        "ci": evidence_rows(registry, evidence, ("ci",)),
        "hook_managers": evidence_rows(registry, evidence, ("hook-manager",)),
        "docs": {
            "dir": config.docs_dir if (root / config.docs_dir).is_dir() else None,
            "index": config.docs_index if (root / config.docs_index).is_file() else None,
            "sites": existing_paths(root, registry.docs_sites),
        },
        "symlinks": [
            {"path": link, "expected": link_expectation(link, target), "state": state, "points_to": actual or None}
            for link, target in claude_links(claude, config, owned_paths(root, registry))
            for state, actual in [link_state(root, link, target)]
        ],
        "always_loaded": {
            "bytes": loaded.total_bytes,
            "tokens": loaded.tokens(config.bytes_per_token),
            "bytes_per_token": config.bytes_per_token,
            "files": [name for name, _ in loaded.files],
        },
        "notes": shared_hook_notes(root, targets) + tool_notes(registry, evidence) + flagged_file_notes(root, registry),
    }


def joined_or_none(values: List[str]) -> str:
    return ", ".join(values) if values else "none"


def evidence_label(row: dict) -> str:
    return f"{row['name']} ({joined_or_none(row['evidence'])})"


def print_inventory(report: dict) -> None:
    print(f"Repository: {report['root']} (files from {report['file_listing']})")
    print(f"Agents detected: {joined_or_none(report['agents_detected'])}")
    print(f"Targets ({report['targets_from']}): {joined_or_none(report['targets'])}")
    print("Instruction files:" + ("" if report["instruction_files"] else " none"))
    for entry in report["instruction_files"]:
        detail = f"-> {entry['symlink_to']}" if "symlink_to" in entry else f"{entry.get('bytes', 0)} bytes, {entry.get('lines', 0)} lines"
        print(f"  {entry['path']}{' (nested)' if entry['nested'] else ''}  {detail}")
    print(f"CLAUDE.md: {CLAUDE_MD_DESCRIPTIONS[report['claude_md']]}")

    def directories(entries: List[dict], unit: str) -> str:
        return joined_or_none([f"{entry['path']} -> {entry['symlink_to']}" if "symlink_to" in entry else f"{entry['path']} ({entry[unit]} {unit})" for entry in entries])

    print(f"Path rules: {directories(report['path_rule_dirs'], 'files')}")
    print(f"Skills: {directories(report['skills_dirs'], 'skills')}")
    print(f"MCP configs: {joined_or_none(report['mcp_configs'])}")
    print(f"Ignore files: {joined_or_none(report['ignore_files'])}")
    print(f"Hooks files: {joined_or_none([row['path'] for row in report['hooks_files']])}")
    for label, key in (("Review bots", "review_bots"), ("Generators", "generators"), ("CI", "ci"), ("Hook manager", "hook_managers")):
        print(f"{label}: {joined_or_none([evidence_label(row) for row in report[key]])}")
    print(f"Cloud-agent setup: {joined_or_none([row['path'] for row in report['cloud_agent_setup']])}")
    docs = report["docs"]
    print(f"Docs: {docs['dir'] or 'no docs directory'}, index {docs['index'] or 'missing'}, site {joined_or_none(docs['sites'])}")
    print("Symlinks: " + "; ".join(f"{row['path']} {row['state']}" + (f" -> {row['points_to']}" if row["points_to"] else "") + ("" if row["state"] == "ok" else f" (expected -> {row['expected']})") for row in report["symlinks"]))
    loaded = report["always_loaded"]
    print(f"Always loaded: ~{loaded['tokens']} tokens ({loaded['bytes']} bytes / {loaded['bytes_per_token']}) from {joined_or_none(loaded['files'])}")
    for note in report["notes"]:
        print(f"Note: {note}")


def run_inventory(arguments) -> int:
    root, registry = resolve_root(arguments.repo), resolve_registry(arguments.registry)
    config = load_config(root, registry)
    if arguments.bytes_per_token:
        config = replace(config, bytes_per_token=arguments.bytes_per_token)
    report = inventory_report(root, registry, config)
    if arguments.json:
        print(json.dumps(report, indent=2))
    else:
        print_inventory(report)
    return 0


def run_layout(arguments) -> int:
    root, registry = resolve_root(arguments.repo), resolve_registry(arguments.registry)
    config, budget_derivation = layout_config(root, registry, arguments.targets)
    steps = plan_layout(root, registry, config, arguments.targets, budget_derivation)
    print(f"{'Applied to' if arguments.apply else 'Plan for'} {root}{'' if arguments.apply else ' (dry run; --apply writes it)'}:")
    for step in steps:
        if arguments.apply and step.action:
            step.action()
        print(f"{step.status:<6}  {step.path}  {step.detail}")
    return 1 if any(step.status == "manual" for step in steps) else 0


def run_generate(arguments) -> int:
    root, registry = resolve_root(arguments.repo), resolve_registry(arguments.registry)
    config = load_config(root, registry)
    rules, _ = read_rules(root, config.rules_dir, owned_paths(root, registry))
    plan = plan_generation(root, registry, config, rules)
    blocked = any(rule.error for rule in rules if not rule.owned)
    if not arguments.check and not blocked:
        apply_changes(root, plan.changes)
    verb = "would " if arguments.check or blocked else ""
    for change in plan.changes:
        print(f"{verb}{change.action} {change_line(change)}")
    for note in plan.notes:
        print(f"note: {note}")
    for problem in plan.problems:
        print(f"FAIL: {problem.message}")
        if problem.detail and not arguments.check:
            print(problem.detail)
    if blocked:
        print("FAIL: nothing was written; fix the rules above first.")
    if not plan.changes and not plan.problems:
        print(f"{GENERATE_COMMAND}: every generated file is up to date")
    if plan.problems or blocked:
        return 1
    return 1 if arguments.check and plan.changes else 0


def run_check(arguments) -> int:
    root, registry = resolve_root(arguments.repo), resolve_registry(arguments.registry)
    config = load_config(root, registry)
    if arguments.bytes_per_token:
        config = replace(config, bytes_per_token=arguments.bytes_per_token)
    findings, loaded = check_findings(root, registry, config)
    budget = config.token_budget if config.token_budget is not None else "none"
    print(f"info: every session loads about {loaded.tokens(config.bytes_per_token)} tokens ({loaded.total_bytes} bytes / {config.bytes_per_token}; budget {budget}) from {joined_or_none([name for name, _ in loaded.files])}")
    for finding in findings:
        print(f"FAIL: {finding}")
    print(f"agent_setup.py check: {len(findings)} finding{'' if len(findings) == 1 else 's'}" if findings else "agent_setup.py check: clean")
    return 1 if findings else 0


def build_parser() -> argparse.ArgumentParser:
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("repo", nargs="?", default=".", help="repository root (default: the current directory)")
    common.add_argument("--registry", help="tool registry JSON (default: assets/targets.json beside scripts/, or targets.json next to this script)")
    ratio_help = f"bytes per token for the estimate (default: bytes_per_token in {CONFIG_FILE}, else ${BYTES_PER_TOKEN_VARIABLE}, else 2.9, measured on Markdown instruction files with claude -p /context)"
    parser = argparse.ArgumentParser(prog="agent_setup.py", description=__doc__, epilog=GLOB_DIALECT, formatter_class=argparse.RawDescriptionHelpFormatter)
    commands = parser.add_subparsers(dest="command", required=True, metavar="command")

    inventory = commands.add_parser("inventory", parents=[common], help="report what the repository has for agents", description="Report instruction files, path-rule and skills directories, MCP, ignore and hooks files, review bots, cloud-agent setup, generators, CI, hook manager, docs, the .claude symlinks and the always-loaded token estimate.")
    inventory.add_argument("--json", action="store_true", help="print the report as JSON")
    inventory.add_argument("--bytes-per-token", type=positive_ratio, help=ratio_help)
    inventory.set_defaults(handler=run_inventory)

    layout = commands.add_parser("layout", parents=[common], help="plan, or with --apply write, the canonical layout", description=f"Plan {CONFIG_FILE}, AGENTS.md, CLAUDE.md = @AGENTS.md, the docs index, the rules directory, the skills directory, the .claude/rules and .claude/skills symlinks and the .gitignore entries. A new {CONFIG_FILE} gets token_budget = what every session will load, plus {BUDGET_HEADROOM_PERCENT}%, rounded up to the next {BUDGET_STEP}. Exits 1 while a step needs a person.")
    layout.add_argument("--apply", action="store_true", help="write the plan; a second run changes nothing")
    layout.add_argument("--targets", help=f"comma-separated tool ids for a new {CONFIG_FILE} (default: the detected tools); {ALWAYS_TARGETED} is always included")
    layout.set_defaults(handler=run_layout)

    generate = commands.add_parser("generate", parents=[common], help="write each enabled tool's rule files from the rules directory", description="Generate every enabled target's path-rule files and the CodeRabbit filePatterns block from the flat rules directory, delete generated files whose rule is gone, and never overwrite a file without the generated marker.", epilog=GLOB_DIALECT, formatter_class=argparse.RawDescriptionHelpFormatter)
    generate.add_argument("--check", action="store_true", help="write nothing; exit 1 listing every file that would change")
    generate.set_defaults(handler=run_generate)

    check = commands.add_parser("check", parents=[common], help="the CI gate", description="Fail, one line per finding, on: CLAUDE.md not starting with @AGENTS.md, a missing or wrong .claude symlink, generated files out of date, a rule without paths, with a glob matching nothing, over the line limit or in a subdirectory, a broken relative link or anchor, a doc missing from the docs index, the always-loaded estimate over token_budget, AGENTS.md over its byte cap, and agent files git does not track.", epilog=GLOB_DIALECT, formatter_class=argparse.RawDescriptionHelpFormatter)
    check.add_argument("--bytes-per-token", type=positive_ratio, help=ratio_help)
    check.set_defaults(handler=run_check)
    return parser


def main(argv: Optional[List[str]] = None) -> int:
    arguments = build_parser().parse_args(argv)
    try:
        return arguments.handler(arguments)
    except UsageError as error:
        print(f"agent_setup.py: {error}", file=sys.stderr)
        return 2
    except OSError as error:
        print(f"agent_setup.py: {error.filename or ''}: {error.strerror}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
